__package_name__ = 'base_juno'
__authors__ = 'Alejandra Hernández Segura'
__email__ = 'alejandra.hernandez.segura@rivm.nl'
__license__ = 'AGPLv3'
__version__ = '0.2.4'
__description__ = 'The base_juno library contains basic classes to make a bacteriology genomics pipeline with the format used in the IDS-bioinformatics department (RIVM)'
